export const users = [
    {
        id: "1",
        name: 'Neil Sims',
        email: 'neil.sims@flowbite.com',
        position: 'React Developer',
        status: 'Online',
        check: true,
        image: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
    },
    {
        id: "2",
        name: 'Bonnie Green',
        email: 'bonnie@flowbite.com',
        position: 'Designer',
        status: 'Online',
        check: true,
        image: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
    },
    {
        id: "3",
        name: 'Jese Leos',
        email: 'jese@flowbite.com',
        position: 'Vue JS Developer',
        status: 'Online',
        check: true,
        image: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
    },
    {
        id: "4",
        name: 'Thomas Lean',
        email: 'thomes@flowbite.com',
        position: 'UI/UX Engineer',
        status: 'Online',
        image: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
    },
    {
        id: "5",
        name: 'Leslie Livingston',
        email: 'leslie@flowbite.com',
        position: 'SEO Specialist',
        status: 'Offline',
        check: true,
        image: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
    },
    {
        id: "6",
        name: 'Leslie Livingston',
        email: 'leslie@flowbite.com',
        position: 'SEO Specialist',
        status: 'Offline',
        check: true,
        image: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
    },
    {
        id: "7",
        name: 'Leslie Livingston',
        email: 'leslie@flowbite.com',
        position: 'SEO Specialist',
        status: 'Offline',
        check: false,
        image: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
    },
    {
        id: "8",
        name: 'Leslie Livingston',
        email: 'leslie@flowbite.com',
        position: 'SEO Specialist',
        status: 'Offline',
        check: true,
        image: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
    },
    {
        id: "9",
        name: 'Leslie Livingston',
        email: 'leslie@flowbite.com',
        position: 'SEO Specialist',
        status: 'Offline',
        check: false,
        image: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
    },
    {
        id: "10",
        name: 'Leslie Livingston',
        email: 'leslie@flowbite.com',
        position: 'SEO Specialist',
        status: 'Offline',
        check: false,
        image: 'https://cdn-icons-png.flaticon.com/512/3135/3135715.png',
    },
];